/**
 * Top Movies - OpenAPI 3.0
 * Top Movies Openapi spec.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: marom83@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id?: number;
    username?: string;
    password?: string;
}

